orcid.config:
  type: config_object
  label: 'Orcid config'
  mapping:
    client_id:
      type: text
      label: 'Client ID'
    client_secret:
      type: text
      label: 'Client Secret'
    name_field:
      type: text
      label: 'Name Field'